language: python
python: 2.7
sudo: yes

os:
  - osx

matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode8.3

cache:
  directories:
    - "${HOME}/.pip"

before_cache:
  - "find ${HOME}/.pip -name log -o -name __pycache__ -type d | xargs -I {} rm -rf {}"

install:
  - ansible-playbook travis-ci/setup.sh

before_script:
  - git remote set-branches --add origin master
  - git fetch

script:
  - bash travis-ci/test.sh
